spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    consumer:
      group-id: 'main-consumer'

kafka:
  topics:
    topic-name-1: topic_1
    topic-name-2: topic_2